<div class='auth_form'>
    <div class='header-auth-type'>
        <span class='auth-line add-line'>Авторизация</span>
        <span class='reg-line'>Регистрация</span>
    </div>
    <div class='auth-form-fields bg-dark'>
        <form method='POST' class='form-input-auth'>
            <label class='title-form-auth title-text-form'>Авторизация</label>
            <input name='action' value='auth' hidden>
            <div>
                <label for='name_block_input'>Логин</label>
                <input class='form-control' type='text' required placeholder="логин" id='name_block_input'>
            </div>
            <div>
                <label for='pswd_block_input'>Пароль</label>
                <input id='pswd_block_input' type="password" class='form-control' required placeholder="пароль">
            </div>
            <button type='submit' class="btn btn-success btn-glow">Войти</button>
        </form>            
    </div>
</div>

<style>
  

</style>