<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WORDMASTER</title>
    <link rel="stylesheet" href="./styles/style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="<?=ROOT_PATH?>/css/styles.css">
  </head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
<div class="card-body navbar-dark bg-dark">
    <div class='container'>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark header-navbar">

            <div class="d-flex">
                <a class="navbar-brand site-title" href="<?=ROOT_PATH?>">WORDMASTER</a>
            </div>

            <div class='menu_header'>

            </div>
            
            <div class="d-flex">
                <?php if (empty($this->user->id)){  ?>
                    <a class="btn btn-light" type='button' href='<?=ROOT_PATH?>/user/auth/'>
                        Авторизация
                    </a>
                <?php } else{ ?>
                    <a class="btn btn-light" type='button' href='<?=ROOT_PATH?>/user/logout/'>
                        Выход, <?= $this->user->name . ' ' . $this->user->surname?> 
                    </a>
                    <?php } ?>
            </div>
        </nav>
    </div> 
</div>


